### ISSUE TITLE
Update the delete plugin to check if the source doc exists or not

### ISSUE THREAD

**Issue by dylandepass** [adobe/aem-sidekick#181] opened 2024-06-12 18:11 UTC
Currently the delete plugin assumes we have `status.edit?.status` which we no longer do after load.

https://github.com/adobe/aem-sidekick/blob/main/src/extension/app/plugins/delete/delete.js#L49

**Comment by rofe** [comment] 2024-06-13 07:47
Duplicate of #159

**Closed by rofe** 2024-06-13 07:47 UTC
Labels: bug
